spring:
  datasource:
      url: jdbc:mysql://15.165.199.90:3306/elecsWiki
      username: zangsu
      password: zangsu1120
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    mvc:
      hiddenmethod:
        filter:
          enabled: true
  logging:
    level:
      org.hibernate.SQL: debug
